version: '3.8'

services:

  part6:
    image: burtonma:part5
    container_name: part6
    tty: true                                         
    user: root                                        

  proxy:
    image: nginx:latest
    container_name: proxy                       
    depends_on:
      - part6                                 
    ports:
      - "80:8080"                                     
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro   
    tty: true                                         
    user: root                                        
